### ISSUE TITLE
[Request] Steam Deck compatibility

### ISSUE THREAD

**Issue by pakoito** [ow-mods/ow-mod-manager#180]
As Outer Wilds is compatible with Steam Deck out of the box, it'd be great if this mod manager and all related mods would be too. Electron shouldn't be terribly hard to configure for the Deck's official Linux install.

**Comment by pakoito** [comment]
I'm also volunteering to test it on my Deck, maybe even PR if this ticket is accepted :)

**Comment by joffie87** [comment]
Yea I'm in the same boat. I would love you guys to support linux, particularly the steam deck, but ideally linux in general.

**Comment by BUNN1E5** [comment]
@pakoito @joffie87 There is a workaround to get the mod manager working on Linux. It is a bit jank but it does work nonetheless. Ultimately the problem with the mod manager is not the manager itself (it works on linux fine for the most part) but rather [OWML](https://github.com/ow-mods/owml) as it requires .NET 48 whichis unsupported with mono and is slightly broken in wine

Check out this [repo](https://github.com/BUNN1E5/OuterWildsModManagerLinux) for the Linux installer for the Mod Manager and OWML

And if you are having issues just ping me on the Outer Wilds modding discord

**Comment by hxka** [comment]
That script is very Deck-specific, and doesn't do much other than print the instructions. Thanks for the tip to use older Proton version to install dotnet48, though!

How I installed the mod manager on my system:

1. Set the proton version for the game to 5.0, ran the game once, then quit.
2. ran `protontricks 753640 dotnet48`
3. Unchecked 'Fprce the use of a specific Steam Play compatibility tool' to return to the latest stable Proton version, ran the game once, then quit. (If you've read protontricks help, you might think that you can skip the above steps and just run `PROTON_VERSION="Proton 5.0" protontricks 753640 dotnet48`. This will not work.)
4. Downloaded the mod manger and saved it into ~/Downloads/.
5. Installed it with `protontricks -c '"$WINE" ~/Downloads/OuterWildsModManager-Installer.exe' 753640` (The path to the installer here has to be absolute because protontricks changes working directory)

That's it. Then, to launch the manager, I use `protontricks -c '"$WINE" "C:\Program Files\OuterWildsModManager\OuterWildsModManager.exe"' 753640`. I had to change the game location in the settings and click 'Start Game' once to install the mod loader, though the manager wouldn't be able to start the game. To play the game, I launch it from Steam as usual.

**Comment by BUNN1E5** [comment]
So the main thing the script does is set up the mod manager and the game into 2 separate wine prefixes and then links the mods folders between the 2. This gives the mod manager the ability to actually start the game and to get the logs while the game is running. The exe's goal is to make that easier on most machines.

**Comment by hxka** [comment]
That seems janky as hell. In my setup, one can enter `bash -c 'exec "${@/common\/Outer\ Wilds\/OuterWilds.exe/compatdata\/753640\/pfx\/drive_c\/Program\ Files\/OuterWildsModManager\/OuterWildsModManager.exe}"' -- %command%` as the game's launch options, then launching the game from Steam will launch the mod manager instead. Then, enabling 'Launch game exe directly' will let the manager launch the game.

**Comment by hxka** [comment]
`bash -c 'zenity --question --text "Select what to launch" --ok-label "Outer Wilds" --cancel-label "Outer Wilds Mod Manager" && exec "$@" || exec "${@/common\/Outer\ Wilds\/OuterWilds.exe/compatdata\/753640\/pfx\/drive_c\/Program\ Files\/OuterWildsModManager\/OuterWildsModManager.exe}"' -- %command%`

Put that in the launch options and you'll have a dialog letting you choose to either launch the game directly or launch the mod manager and launch the game through it. And no need for 2 intertwined prefixes shenanigans.

**Comment by MegaPiggy** [comment]
https://github.com/ow-mods/owml/issues/521#issuecomment-1616762398
